"""add is_accessible to attractions

Revision ID: 1894a0d07f91
Revises: 3318164cffec
Create Date: 2026-04-14 19:52:01.758882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1894a0d07f91'
down_revision: Union[str, Sequence[str], None] = '3318164cffec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('is_accessible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attractions', 'is_accessible')
    # ### end Alembic commands ###
