"""add consent field

Revision ID: 2df8e72f5d20
Revises: 5f86dfb51ed0
Create Date: 2026-05-01 20:15:42.305037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df8e72f5d20'
down_revision: Union[str, Sequence[str], None] = '5f86dfb51ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_consent_given', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_consent_given')
    # ### end Alembic commands ###
