"""add category to souvenirs

Revision ID: 6bde054842b9
Revises: 1894a0d07f91
Create Date: 2026-04-14 21:49:02.592184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bde054842b9'
down_revision: Union[str, Sequence[str], None] = '1894a0d07f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('souvenirs', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('souvenirs', 'category')
    # ### end Alembic commands ###
